import { Course, PortalVideoLesson } from '../types';

export const COURSE_VIDEO_PLAYLISTS: Record<string, PortalVideoLesson[]> = {
  // 1. Google AI Studio & Gemini 2.0
  'course-google-ai-studio': [
    {
      id: 'gemini-vid-1',
      title: '01. Google AI Studio (2026) Complete Interface & API Keys Masterclass',
      duration: '14:35',
      company: 'Tech Express',
      youtubeId: '5E3cVP7UYG8',
      youtubeUrl: 'https://www.youtube.com/watch?v=5E3cVP7UYG8',
      description: 'Master Google AI Studio from scratch: API key management, workspace configuration, system instructions, temperature settings, and model selection.',
      badge: 'AI Studio Official • 1080p',
    },
    {
      id: 'gemini-vid-2',
      title: '02. Gemini 2.0 Flash: Practical Guide to Multimodal & Real-Time Features',
      duration: '16:50',
      company: 'AI and Tech for Education',
      youtubeId: 'c-RrIs2taMA',
      youtubeUrl: 'https://www.youtube.com/watch?v=c-RrIs2taMA',
      description: 'Explore Gemini 2.0 Flash breakthrough capabilities: real-time streaming, multimodal audio/vision understanding, document parsing, and ultra-fast inference.',
      badge: 'Gemini 2.0 Flash • Hands-On',
    },
    {
      id: 'gemini-vid-3',
      title: '03. Google AI Studio & Gemini 2.0 Flash: Webcams, Screenshare & Live Audio',
      duration: '13:20',
      company: 'AI For Success',
      youtubeId: '3kYVjGZd8Fw',
      youtubeUrl: 'https://www.youtube.com/watch?v=3kYVjGZd8Fw',
      description: 'Deep dive into live multimodal testing inside Google AI Studio with webcam video analysis, live screen sharing, audio synthesis, and latency benchmarks.',
      badge: 'Multimodal Live Lab',
    },
    {
      id: 'gemini-vid-4',
      title: '04. Building Apps in Google AI Studio: Prompts to Full Working Projects',
      duration: '15:40',
      company: 'Checkmark Academy',
      youtubeId: 'eidxEiJdUbU',
      youtubeUrl: 'https://www.youtube.com/watch?v=eidxEiJdUbU',
      description: 'Step-by-step tutorial on using the Build tab in Google AI Studio to turn natural language prompts into complete, downloadable full-stack applications.',
      badge: 'Vibe Coding & App Build',
    },
    {
      id: 'gemini-vid-5',
      title: '05. Building Full-Stack AI Applications with Andrew Ng & Google GenAI',
      duration: '28:15',
      company: 'DeepLearning.AI',
      youtubeId: 'ff3j4olCUig',
      youtubeUrl: 'https://www.youtube.com/watch?v=ff3j4olCUig',
      description: 'Learn the end-to-end framework for architecting, prototyping, and deploying real production web applications powered by Gemini models and APIs.',
      badge: 'Full-Stack Architecture',
    },
  ],

  // 2. Autonomous AI Agents & Swarms
  'course-autonomous-ai-agents': [
    {
      id: 'agents-vid-1',
      title: '01. What are AI Agents? Autonomous Agency, ReAct & Reasoning Loops',
      duration: '11:45',
      company: 'IBM Technology',
      youtubeId: 'F8NKVhkZZWI',
      youtubeUrl: 'https://www.youtube.com/watch?v=F8NKVhkZZWI',
      description: 'Foundational masterclass on autonomous AI agents: agency, perception-reasoning-action loops, tool use, goal decomposition, and multi-agent coordination.',
      badge: 'IBM Technology • Verified',
    },
    {
      id: 'agents-vid-2',
      title: '02. LangGraph Explained for Beginners: Cyclical Graphs & State Management',
      duration: '14:20',
      company: 'KodeKloud',
      youtubeId: 'cUfLrn3TM3M',
      youtubeUrl: 'https://www.youtube.com/watch?v=cUfLrn3TM3M',
      description: 'Master LangGraph core architecture: converting simple LLM chains into robust cyclical state graphs, conditional routing, nodes, edges, and human-in-the-loop validation.',
      badge: 'LangGraph Production',
    },
    {
      id: 'agents-vid-3',
      title: '03. CrewAI Step-by-Step Complete Course: Building Multi-Agent Teams',
      duration: '45:30',
      company: 'Alejandro AO',
      youtubeId: 'kBXYFaZ0EN0',
      youtubeUrl: 'https://www.youtube.com/watch?v=kBXYFaZ0EN0',
      description: 'Build production multi-agent crews with CrewAI: role assignment, toolkits, hierarchical processes, task delegation, shared memory, and automated workflows.',
      badge: 'CrewAI Multi-Agent Swarms',
    },
    {
      id: 'agents-vid-4',
      title: '04. AutoGen Tutorial for Beginners: Build Your First Multi-Agent App',
      duration: '28:15',
      company: 'Leon van Zyl',
      youtubeId: 'KCoBVe-3Rp8',
      youtubeUrl: 'https://www.youtube.com/watch?v=KCoBVe-3Rp8',
      description: 'Microsoft AutoGen framework guide: create conversational agent teams, UserProxyAgent orchestration, tool calling, code execution, and autonomous collaborative problem-solving.',
      badge: 'Microsoft AutoGen Lab',
    },
    {
      id: 'agents-vid-5',
      title: '05. OpenAI Swarm: Multi-Agent Orchestration & Swarm Workflows',
      duration: '24:10',
      company: 'Cole Medin',
      youtubeId: 'q7_5eCmu0MY',
      youtubeUrl: 'https://www.youtube.com/watch?v=q7_5eCmu0MY',
      description: 'Deep dive into lightweight agent orchestration with OpenAI Swarm: agent handoffs, context variable passing, routines, database tools, and production swarm patterns.',
      badge: 'OpenAI Swarm Architecture',
    },
  ],

  // 3. ChatGPT & OpenAI 6-in-1 Masterclass
  'course-chatgpt-6-openai': [
    {
      id: 'chatgpt-vid-1',
      title: '01. The Ultimate ChatGPT Tutorial: Complete Crash Course from Zero to Pro',
      duration: '38:15',
      company: 'Skillademia',
      youtubeId: 'g5oEAoKdrdw',
      youtubeUrl: 'https://www.youtube.com/watch?v=g5oEAoKdrdw',
      description: 'Master ChatGPT interface, settings, customization, prompting frameworks, vision analysis, and real-world workflows in an in-depth practical guide.',
      badge: 'OpenAI Masterclass • Verified',
    },
    {
      id: 'chatgpt-vid-2',
      title: '02. Mastering OpenAI o1 & o1-Mini Reasoning Models: Complete Guide',
      duration: '18:40',
      company: 'Atef Ataya AI',
      youtubeId: 'wRes6bT58h8',
      youtubeUrl: 'https://www.youtube.com/watch?v=wRes6bT58h8',
      description: 'Deep dive into OpenAI frontier reasoning models (o1, o1-mini, o3-mini): test-time compute, deliberate thought chains, math/logic solving, and API usage.',
      badge: 'Frontier Reasoning',
    },
    {
      id: 'chatgpt-vid-3',
      title: '03. How to Create Custom GPTs: Step-by-Step OpenAI Tutorial',
      duration: '17:50',
      company: 'Kevin Stratvert',
      youtubeId: '0Q1AQAxpdGg',
      youtubeUrl: 'https://www.youtube.com/watch?v=0Q1AQAxpdGg',
      description: 'Complete hands-on guide by Kevin Stratvert: Configure custom instructions, upload private knowledge files, add conversation starters, and publish GPTs.',
      badge: 'Custom GPTs',
    },
    {
      id: 'chatgpt-vid-4',
      title: '04. ChatGPT Canvas Mode Explained: Interactive Writing & Coding Workspace',
      duration: '14:25',
      company: 'techspeeder',
      youtubeId: '3wYT4k46RD0',
      youtubeUrl: 'https://www.youtube.com/watch?v=3wYT4k46RD0',
      description: 'Master ChatGPT Canvas: Real-time side-by-side editing, targeted code debugging, inline writing feedback, length adjustments, and version management.',
      badge: 'Canvas Workspace',
    },
    {
      id: 'chatgpt-vid-5',
      title: '05. Build AI Apps with OpenAI o3-mini & GPT-4o: API, RAG & Tool Calling',
      duration: '42:30',
      company: 'Analytics Vidhya',
      youtubeId: 'WXqTJVN139o',
      youtubeUrl: 'https://www.youtube.com/watch?v=WXqTJVN139o',
      description: 'End-to-end full developer masterclass: OpenAI API keys, function calling, Retrieval-Augmented Generation (RAG), and deploying full-stack AI web apps.',
      badge: 'Developer Full Course',
    },
  ],

  // 4. Claude 3.7 Sonnet Mastery
  'course-claude-mastery': [
    {
      id: 'claude-vid-1',
      title: '01. Claude 3.7 Sonnet Architecture & Extended Thinking Models',
      duration: '16:40',
      company: 'Anthropic AI Engineering',
      youtubeId: 'kBp-PxsotMo',
      youtubeUrl: 'https://www.youtube.com/watch?v=kBp-PxsotMo',
      description: 'Master Claude 3.7 hybrid reasoning: Toggle between near-instant responses and deep step-by-step thinking mode with configurable token budgets.',
      badge: 'Claude 3.7 Mastery • Verified',
    },
    {
      id: 'claude-vid-2',
      title: '02. Interactive Artifacts & Single-File Application Development',
      duration: '18:15',
      company: 'Kevin Stratvert',
      youtubeId: '1PRcdCu8n6M',
      youtubeUrl: 'https://www.youtube.com/watch?v=1PRcdCu8n6M',
      description: 'Step-by-step masterclass on building live React web apps, SVG diagrams, financial calculators, and interactive widgets directly in Claude Artifacts.',
      badge: 'Interactive Artifacts • HD',
    },
    {
      id: 'claude-vid-3',
      title: '03. Prompting 101: Context Optimization & Frontier Engineering',
      duration: '14:50',
      company: 'Anthropic (Official)',
      youtubeId: 'ysPbXH0LpIE',
      youtubeUrl: 'https://www.youtube.com/watch?v=ysPbXH0LpIE',
      description: 'Official Anthropic developer masterclass: Best practices for system prompts, XML tags, structured outputs, and 200k context prompt caching.',
      badge: 'Official Anthropic • 1080p',
    },
    {
      id: 'claude-vid-4',
      title: '04. Claude Projects: Knowledge Bases, Style Guides & Team Workflows',
      duration: '12:35',
      company: 'Anthropic (Official)',
      youtubeId: 'GJ5jTgcbRHA',
      youtubeUrl: 'https://www.youtube.com/watch?v=GJ5jTgcbRHA',
      description: 'Official Anthropic guide on organizing team project spaces, uploading custom docs, setting project instructions, and maintaining persistent context.',
      badge: 'Claude Projects • Official',
    },
    {
      id: 'claude-vid-5',
      title: '05. Claude Computer Use API: Autonomous Desktop & Browser Control',
      duration: '25:20',
      company: 'Anthropic (Official)',
      youtubeId: 'vH2f7cjXjKI',
      youtubeUrl: 'https://www.youtube.com/watch?v=vH2f7cjXjKI',
      description: 'Configure the Anthropic Computer Use API to navigate browser tabs, click UI buttons, extract spreadsheet data, and automate repetitive tasks.',
      badge: 'Computer Use Automation',
    },
  ],

  // 5. DeepSeek R1 & Excel Financial Modeling
  'course-deepseek-finance-excel': [
    {
      id: 'deepseek-vid-1',
      title: '01. DeepSeek R1 Architecture: Chain-of-Thought Reasoning & Open Weights',
      duration: '45:00',
      company: 'freeCodeCamp.org',
      youtubeId: '_CXwZ5xyFno',
      youtubeUrl: 'https://www.youtube.com/watch?v=_CXwZ5xyFno',
      description: 'Comprehensive DeepSeek-R1 deep dive: reinforcement learning without supervised fine-tuning, reasoning tokens, benchmark comparisons, and practical applications.',
      badge: 'freeCodeCamp • DeepSeek Core',
    },
    {
      id: 'deepseek-vid-2',
      title: '02. Integrating DeepSeek into Microsoft Excel: Automated Formulas & Analysis',
      duration: '18:20',
      company: 'Sven Bosau',
      youtubeId: 'ln8oxm9Gvjs',
      youtubeUrl: 'https://www.youtube.com/watch?v=ln8oxm9Gvjs',
      description: 'Step-by-step guide to connect DeepSeek with Microsoft Excel: automated formula generation, table parsing, custom VBA functions, and live spreadsheet prompt execution.',
      badge: 'DeepSeek in Excel',
    },
    {
      id: 'deepseek-vid-3',
      title: '03. Three-Statement Financial Modeling in Excel: Income, Balance & Cash Flow',
      duration: '32:45',
      company: 'Corporate Finance Institute',
      youtubeId: 'UMYDxmiVin4',
      youtubeUrl: 'https://www.youtube.com/watch?v=UMYDxmiVin4',
      description: 'Institutional 3-statement financial modeling tutorial with CFI CEO Tim Vipond: linking income statement, balance sheet, and cash flow with dynamic error-checking.',
      badge: 'CFI Financial Modeling',
    },
    {
      id: 'deepseek-vid-4',
      title: '04. Run DeepSeek-R1 Locally with Ollama: 100% Private Offline Financial Data',
      duration: '15:30',
      company: 'ZazenCodes',
      youtubeId: 'dS9Vbye-xSY',
      youtubeUrl: 'https://www.youtube.com/watch?v=dS9Vbye-xSY',
      description: 'Setup and run DeepSeek-R1 locally using Ollama: pull quantized models, interact via CLI and API, and process confidential financial data without internet exposure.',
      badge: 'Local Ollama & Privacy',
    },
    {
      id: 'deepseek-vid-5',
      title: '05. Financial Modeling Essentials & Valuation: Scenario Tables & Forecasting',
      duration: '28:15',
      company: 'Kenji Explains',
      youtubeId: '64A6HJDEbKA',
      youtubeUrl: 'https://www.youtube.com/watch?v=64A6HJDEbKA',
      description: 'Master financial modeling essentials in Excel: dynamic revenue drivers, scenario managers, DCF valuation assumptions, and executive dashboard design.',
      badge: 'Financial Valuation & DCF',
    },
  ],

  // 6. Cursor AI & AI Pair Programming
  'course-cursor-copilot-coding': [
    {
      id: 'cursor-vid-1',
      title: '01. Cursor AI Tutorial for Beginners: Getting Started & Faster Coding',
      duration: '18:45',
      company: 'Volo Builds',
      youtubeId: 'yk9lXobJ95E',
      youtubeUrl: 'https://www.youtube.com/watch?v=yk9lXobJ95E',
      description: 'Comprehensive walkthrough of Cursor AI: installation, setting up AI models, Composer (Cmd+I), inline code editing (Cmd+K), and prompt engineering for clean code.',
      badge: 'Cursor Essentials • Verified',
    },
    {
      id: 'cursor-vid-2',
      title: '02. How to Use GitHub Copilot: The Complete Beginner\'s Guide',
      duration: '15:30',
      company: 'GitHub (Official)',
      youtubeId: 'SJqGYwRq0uc',
      youtubeUrl: 'https://www.youtube.com/watch?v=SJqGYwRq0uc',
      description: 'Official GitHub guide: setting up GitHub Copilot in VS Code, inline completions, Copilot Chat, generating unit tests, writing documentation, and terminal commands.',
      badge: 'GitHub Official • Beginner\'s Guide',
    },
    {
      id: 'cursor-vid-3',
      title: '03. Build a Full-Stack Web App from Scratch with Cursor AI & Composer',
      duration: '42:15',
      company: 'RoadsideCoder',
      youtubeId: 'k5x3pasUJPs',
      youtubeUrl: 'https://www.youtube.com/watch?v=k5x3pasUJPs',
      description: 'Hands-on project building: Create a full-stack web application using Cursor Composer, Agent mode, project rules, skills, bug fixing with Bugbot, and Git integration.',
      badge: 'Full-Stack Project Build',
    },
    {
      id: 'cursor-vid-4',
      title: '04. Cursor vs. GitHub Copilot: Real-World Workflow & Tool Comparison',
      duration: '14:20',
      company: 'Bryan Software',
      youtubeId: 'IgcNX3fUoMQ',
      youtubeUrl: 'https://www.youtube.com/watch?v=IgcNX3fUoMQ',
      description: 'In-depth comparative analysis testing both Cursor and GitHub Copilot: multi-file context retention, speed, code quality, pricing, and when to use each in production.',
      badge: 'Cursor vs Copilot Benchmark',
    },
    {
      id: 'cursor-vid-5',
      title: '05. Cursor Crash Course & AI Coding for Modern Web Developers',
      duration: '31:40',
      company: 'Traversy Media',
      youtubeId: '5zR1ZE5aqho',
      youtubeUrl: 'https://www.youtube.com/watch?v=5zR1ZE5aqho',
      description: 'Master professional AI-assisted workflows: refactoring legacy code, building full frontend interfaces, handling API integrations, and deploying production apps.',
      badge: 'Traversy Media • Crash Course',
    },
  ],

  // 7. Cinematic AI Video Filmmaking
  'course-ai-video-filmmaking': [
    {
      id: 'video-vid-1',
      title: '01. Professional AI Filmmaking: Step-by-Step AI Film Production Pipeline',
      duration: '22:15',
      company: 'Curious Refuge',
      youtubeId: 'wHIdCNIQHpo',
      youtubeUrl: 'https://www.youtube.com/watch?v=wHIdCNIQHpo',
      description: 'Master the end-to-end AI film production workflow: ideation, storyboarding, character design, cinematic shot generation, and post-production assembly.',
      badge: 'Curious Refuge • AI Cinema',
    },
    {
      id: 'video-vid-2',
      title: '02. Cinematic AI Videos with Runway Gen-3: Camera Controls & Motion Prompts',
      duration: '18:40',
      company: 'Curious Refuge',
      youtubeId: 'gyCg0yv3Njw',
      youtubeUrl: 'https://www.youtube.com/watch?v=gyCg0yv3Njw',
      description: 'Direct AI cameras with exact precision in Runway Gen-3: Motion Brush, camera speed curves, panning, Dutch angles, rack focus, and cinematic prompt structure.',
      badge: 'Runway Gen-3 Cinematics',
    },
    {
      id: 'video-vid-3',
      title: '03. Photorealistic AI Avatars & Lip-Sync: Complete HeyGen Studio Tutorial',
      duration: '19:30',
      company: 'Simon Crowe',
      youtubeId: 'RTmlxuroR50',
      youtubeUrl: 'https://www.youtube.com/watch?v=RTmlxuroR50',
      description: 'Create your digital twin avatar, generate expressive speaking head videos, customize backgrounds, and translate content across 40+ languages with seamless lip-sync.',
      badge: 'HeyGen Avatars & Lip-Sync',
    },
    {
      id: 'video-vid-4',
      title: '04. AI Voice Cloning & Audio Design: ElevenLabs Voice Studio Masterclass',
      duration: '16:45',
      company: 'Kevin Stratvert',
      youtubeId: 'yDTbAxJ3sKI',
      youtubeUrl: 'https://www.youtube.com/watch?v=yDTbAxJ3sKI',
      description: 'Professional voice cloning and audio generation with ElevenLabs: instant vs professional voice clones, emotion modulation, stability sliders, and AI sound effects.',
      badge: 'ElevenLabs Voice AI',
    },
    {
      id: 'video-vid-5',
      title: '05. AI Video Assembly in CapCut: Auto-Captions, Sound Effects & Viral Reels',
      duration: '25:10',
      company: 'Ben Kimball AI',
      youtubeId: 'w6C8uvusMDg',
      youtubeUrl: 'https://www.youtube.com/watch?v=w6C8uvusMDg',
      description: 'Combine AI footage into viral social media reels and commercial ads: AI auto-captions, background removal, beat-matched transitions, and 4K export settings.',
      badge: 'CapCut AI & Viral Reels',
    },
  ],

  // 8. Voice AI & Realtime Telephony Calling Agents
  'course-voice-ai-telephony': [
    {
      id: 'voice-vid-1',
      title: '01. Building Realtime Voice AI Agents: Architecture, LiveKit & Python Pipeline',
      duration: '18:15',
      company: 'AgenticXLab',
      youtubeId: '3SA6J8xIoYk',
      youtubeUrl: 'https://www.youtube.com/watch?v=3SA6J8xIoYk',
      description: 'Architecture of sub-500ms conversational voice agents: Speech-to-Text (Deepgram), LLM orchestration, and Text-to-Speech (ElevenLabs) with LiveKit WebRTC transport.',
      badge: 'AgenticXLab • Architecture',
    },
    {
      id: 'voice-vid-2',
      title: '02. Vapi AI Voice Agent Masterclass: System Prompts, Latency Tuning & Voices',
      duration: '17:40',
      company: 'Kingy AI',
      youtubeId: 'ZmebRZOXV28',
      youtubeUrl: 'https://www.youtube.com/watch?v=ZmebRZOXV28',
      description: 'Complete guide to building conversational voice bots in Vapi: prompt engineering for natural flow, background ambiance, filler words, and low-latency voice models.',
      badge: 'Vapi AI Masterclass',
    },
    {
      id: 'voice-vid-3',
      title: '03. Connecting Twilio Phone Numbers to Voice AI: Inbound & Outbound Telephony',
      duration: '16:20',
      company: 'Toshiki Kodaira',
      youtubeId: 'q0OTlaDy0oQ',
      youtubeUrl: 'https://www.youtube.com/watch?v=q0OTlaDy0oQ',
      description: 'Step-by-step setup connecting Twilio telephone numbers to Vapi voice agents: SIP trunk routing, inbound call handling, and outbound phone campaign configurations.',
      badge: 'Twilio Telephony & SIP',
    },
    {
      id: 'voice-vid-4',
      title: '04. Real-Time Voice Function Calling: Live Google Calendar Appointment Booking',
      duration: '21:10',
      company: 'Austin Peechatt',
      youtubeId: '8fl9XJ7RWbU',
      youtubeUrl: 'https://www.youtube.com/watch?v=8fl9XJ7RWbU',
      description: 'Enable your voice agent to execute live tools: checking availability, booking appointments directly on Google Calendar, and sending instant confirmation SMS/emails.',
      badge: 'Calendar Booking & Tools',
    },
    {
      id: 'voice-vid-5',
      title: '05. Building Full-Stack AI Voice Agents with LiveKit: WebRTC & Voice Pipelines',
      duration: '24:50',
      company: 'Ashton Voss',
      youtubeId: 'EHphVIGiWKU',
      youtubeUrl: 'https://www.youtube.com/watch?v=EHphVIGiWKU',
      description: 'Full beginner-to-pro guide to building conversational voice AI using LiveKit: Deepgram STT, real-time LLM inference, ElevenLabs voice synthesis, and turn detection.',
      badge: 'LiveKit & WebRTC Voice',
    },
  ],

  // 9. Zapier & Webhook AI Automations
  'course-zapier-ai-automation': [
    {
      id: 'zapier-vid-1',
      title: '01. Zapier AI Tutorial for Beginners: Automation Made Simple',
      duration: '16:15',
      company: 'Kevin Stratvert',
      youtubeId: 'JtdUgJGI_Oo',
      youtubeUrl: 'https://www.youtube.com/watch?v=JtdUgJGI_Oo',
      description: 'Master Zapier fundamentals from zero: connect apps, configure triggers and actions, build your first automated Zap, and leverage AI workflow generation.',
      badge: 'Automation Engineering • Verified',
    },
    {
      id: 'zapier-vid-2',
      title: '02. Multi-Step Zaps & Paths: Conditional Branching & Logic in Zapier',
      duration: '18:20',
      company: 'Tom Nassr • XRAY Automation',
      youtubeId: '7PIUFcQikhI',
      youtubeUrl: 'https://www.youtube.com/watch?v=7PIUFcQikhI',
      description: 'Build advanced multi-step Zaps with Paths and conditional logic: filter criteria, branch execution trails, and route data dynamically.',
      badge: 'Conditional Branching',
    },
    {
      id: 'zapier-vid-3',
      title: '03. Zapier AI Beginners Guide: AI Agents & Automated Workflows',
      duration: '15:40',
      company: 'AI Master',
      youtubeId: 'm-kWrOvA49U',
      youtubeUrl: 'https://www.youtube.com/watch?v=m-kWrOvA49U',
      description: 'Integrate AI natively into Zapier: Deploy Zapier Agents, connect LLMs to your data stack, and automate content summarization and customer response pipelines.',
      badge: 'AI-Powered Zaps',
    },
    {
      id: 'zapier-vid-4',
      title: '04. Webhooks by Zapier: Catch Hooks, REST APIs & Live Triggers',
      duration: '17:10',
      company: 'Jeet Sangamnerkar • Operations Automation',
      youtubeId: '85JFT58gDoE',
      youtubeUrl: 'https://www.youtube.com/watch?v=85JFT58gDoE',
      description: 'Master Catch Webhooks and Custom Requests in Zapier: Connect payment gateways (Stripe, Razorpay), custom frontend forms, and parse nested JSON payloads.',
      badge: 'Webhooks & REST APIs',
    },
    {
      id: 'zapier-vid-5',
      title: '05. Master Automation with Zapier & AI Agents: Complete 4-Hour Course',
      duration: '4:12:00',
      company: 'freeCodeCamp.org',
      youtubeId: '-leIp449qXA',
      youtubeUrl: 'https://www.youtube.com/watch?v=-leIp449qXA',
      description: 'Comprehensive full-length masterclass from freeCodeCamp: End-to-end automation architecture, AI agents, MCP protocol, error handling, and business workflows.',
      badge: 'Full Masterclass • 4-Hour',
    },
  ],

  // 10. Midjourney v6 & AI Visuals
  'course-midjourney-visuals': [
    {
      id: 'midjourney-vid-1',
      title: '01. Complete Beginners Guide to Midjourney v6: Prompting & Parameters',
      duration: '22:15',
      company: 'Tao Prompts',
      youtubeId: '9F-hgjb6PCE',
      youtubeUrl: 'https://www.youtube.com/watch?v=9F-hgjb6PCE',
      description: 'Master Midjourney v6 fundamentals from scratch: camera focal lengths, lighting prompts, aspect ratios (--ar), stylize, chaos, and photorealistic rendering formulas.',
      badge: 'Midjourney v6 • Verified',
    },
    {
      id: 'midjourney-vid-2',
      title: '02. Character Consistency in Midjourney: Character Reference (--cref & --cw)',
      duration: '14:40',
      company: 'Curious Refuge',
      youtubeId: '7BO_TocisAc',
      youtubeUrl: 'https://www.youtube.com/watch?v=7BO_TocisAc',
      description: 'Lock facial features, clothing, and hairstyles across dozens of scenes using --cref and --cw parameters to illustrate books, advertisements, and social content.',
      badge: 'Character Consistency',
    },
    {
      id: 'midjourney-vid-3',
      title: '03. Ideogram 2.0 Typography & Graphic Design: Flawless Text & Logos',
      duration: '16:20',
      company: 'Qudata Creative',
      youtubeId: '3Zi-yfxZac4',
      youtubeUrl: 'https://www.youtube.com/watch?v=3Zi-yfxZac4',
      description: 'Generate advertising posters, merchandise logos, and graphic layouts with zero misspelled text, using Ideogram 2.0 styles, color palettes, and Magic Prompt.',
      badge: 'Ideogram Typography',
    },
    {
      id: 'midjourney-vid-4',
      title: '04. Photoshop Generative Fill & Firefly: The Ultimate Guide to AI Editing',
      duration: '18:35',
      company: 'Brendan Williams',
      youtubeId: 'SB60EQG2HyE',
      youtubeUrl: 'https://www.youtube.com/watch?v=SB60EQG2HyE',
      description: 'Seamlessly expand image borders with Generative Expand, remove unwanted objects, inpaint textures, and blend multi-layer AI graphics in Adobe Photoshop.',
      badge: 'Photoshop Generative Fill',
    },
    {
      id: 'midjourney-vid-5',
      title: '05. Midjourney Vector Art & SVG Conversion: Print-Ready 300 DPI Exports',
      duration: '12:50',
      company: 'Wade McMaster • Creator Impact',
      youtubeId: 'OBqMU-fp8O0',
      youtubeUrl: 'https://www.youtube.com/watch?v=OBqMU-fp8O0',
      description: 'Convert Midjourney raster artwork into infinite-resolution SVG vectors with Vectorizer.AI, preparing commercial graphics for merchandise, print, and logos.',
      badge: 'Vector & Print Workflows',
    },
  ],

  // 11. Generative AI for Beginners
  'course-genai-beginners': [
    {
      id: 'genai-vid-1',
      title: '01. What Are Generative AI Models? Complete Foundation Masterclass',
      duration: '08:45',
      company: 'IBM Technology',
      youtubeId: 'hfIUstzHs9A',
      youtubeUrl: 'https://www.youtube.com/watch?v=hfIUstzHs9A',
      description: 'Foundational plain-English guide to Generative AI, Large Language Models, foundation architectures, and how AI generates original text, images, and solutions.',
      badge: 'Foundation • IBM Verified',
    },
    {
      id: 'genai-vid-2',
      title: '02. Master the Perfect Prompt Formula: Role, Task, Context, Steps & Format',
      duration: '08:20',
      company: 'Jeff Su Productivity',
      youtubeId: 'jC4v5AS4RIM',
      youtubeUrl: 'https://www.youtube.com/watch?v=jC4v5AS4RIM',
      description: 'Learn the exact 5-part prompt blueprint used to get accurate, high-quality, hallucination-free outputs from ChatGPT, Gemini, and Claude on your first try.',
      badge: 'Prompt Blueprint',
    },
    {
      id: 'genai-vid-3',
      title: '03. Generative AI for Beginners: Everyday AI Tools & Workflow Automation',
      duration: '14:15',
      company: 'MaxonShire AI',
      youtubeId: 'ahoH1s13LZE',
      youtubeUrl: 'https://www.youtube.com/watch?v=ahoH1s13LZE',
      description: 'Hands-on beginner tour of the leading Generative AI tools for daily productivity: email drafting, document summarization, idea generation, and daily organization.',
      badge: 'Everyday Tools',
    },
    {
      id: 'genai-vid-4',
      title: '04. AI Hallucinations Simply Explained: How LLMs Think, Tokens & Fact-Checking',
      duration: '07:50',
      company: 'codebasics',
      youtubeId: 'xaEgbDa1KSI',
      youtubeUrl: 'https://www.youtube.com/watch?v=xaEgbDa1KSI',
      description: 'Understand why AI models hallucinate or make things up, how token prediction works under the hood, and practical strategies to fact-check generated answers.',
      badge: 'LLM Mechanics',
    },
    {
      id: 'genai-vid-5',
      title: '05. AI Ethics, Digital Privacy & Responsible Generative AI 101',
      duration: '12:15',
      company: 'John Moore Tech',
      youtubeId: '6fwhbzcUM38',
      youtubeUrl: 'https://www.youtube.com/watch?v=6fwhbzcUM38',
      description: 'Critical safety principles for the generative AI era: protecting sensitive personal information, recognizing copyright issues, and deploying AI responsibly.',
      badge: 'AI Safety & Ethics',
    },
  ],

  // 12. Claude AI for Beginners
  'course-claude-beginners': [
    {
      id: 'claudebeg-vid-1',
      title: '01. Claude AI Complete Interface & Capabilities Walkthrough',
      duration: '16:40',
      company: 'Anthropic AI Engineering',
      youtubeId: 'kBp-PxsotMo',
      youtubeUrl: 'https://www.youtube.com/watch?v=kBp-PxsotMo',
      description: 'Getting started with Claude: Creating your free account, exploring chat models, uploading documents, and setting up initial preferences.',
      badge: 'Claude Fundamentals',
    },
    {
      id: 'claudebeg-vid-2',
      title: '02. Claude Artifacts: Creating Real-Time Web Apps & Interactive Visuals',
      duration: '18:15',
      company: 'Kevin Stratvert',
      youtubeId: '1PRcdCu8n6M',
      youtubeUrl: 'https://www.youtube.com/watch?v=1PRcdCu8n6M',
      description: 'Watch Claude generate interactive HTML calculators, responsive diagrams, and complete React code components side-by-side with your chat.',
      badge: 'Interactive Artifacts',
    },
    {
      id: 'claudebeg-vid-3',
      title: '03. Prompting 101: Context Optimization & Writing Guides',
      duration: '14:50',
      company: 'Anthropic (Official)',
      youtubeId: 'ysPbXH0LpIE',
      youtubeUrl: 'https://www.youtube.com/watch?v=ysPbXH0LpIE',
      description: 'Official Anthropic guide on writing voice matching, clear system constraints, and prompt caching to maximize Claude context.',
      badge: 'Style & Voice Matching',
    },
    {
      id: 'claudebeg-vid-4',
      title: '04. Claude Projects: Managing Knowledge Bases & PDF Documents',
      duration: '12:35',
      company: 'Anthropic (Official)',
      youtubeId: 'GJ5jTgcbRHA',
      youtubeUrl: 'https://www.youtube.com/watch?v=GJ5jTgcbRHA',
      description: 'Upload research papers, legal agreements, and Excel exports into custom Claude Project knowledge bases.',
      badge: 'Claude Projects',
    },
    {
      id: 'claudebeg-vid-5',
      title: '05. Thinking Mode & Multi-Step Logic: Autonomous Desktop Automation',
      duration: '25:20',
      company: 'Anthropic (Official)',
      youtubeId: 'vH2f7cjXjKI',
      youtubeUrl: 'https://www.youtube.com/watch?v=vH2f7cjXjKI',
      description: 'Activate Claude extended thinking mode to solve complex logical problems, write multi-step strategies, and run autonomous tasks.',
      badge: 'Computer Use Automation',
    },
  ],

  // 13. AI for Teachers & Educators
  'course-ai-teachers': [
    {
      id: 'teachers-vid-1',
      title: '01. AI for Teachers: Complete Lesson Planning from Scratch in Minutes',
      duration: '18:40',
      company: 'Designed for Learning',
      youtubeId: 'akykzhYEBWU',
      youtubeUrl: 'https://www.youtube.com/watch?v=akykzhYEBWU',
      description: 'Masterclass on generating standards-aligned lesson plans, pedagogical hooks, board activities, and step-by-step teaching guides with AI.',
      badge: 'Lesson Planning • HD',
    },
    {
      id: 'teachers-vid-2',
      title: '02. Differentiated Learning: Customizing Class Materials with AI (Diffit)',
      duration: '14:25',
      company: 'Edutopia',
      youtubeId: 'k3bBAIyy-7E',
      youtubeUrl: 'https://www.youtube.com/watch?v=k3bBAIyy-7E',
      description: 'Official Edutopia walkthrough: Automatically adapt reading levels, vocabulary tiers, and challenge questions so both fast and slow learners thrive.',
      badge: 'Edutopia Verified • HD',
    },
    {
      id: 'teachers-vid-3',
      title: '03. Automated Rubric Generator & Objective Grading Assistance',
      duration: '12:50',
      company: 'EzLessonHub',
      youtubeId: 'o48T9FK9VwI',
      youtubeUrl: 'https://www.youtube.com/watch?v=o48T9FK9VwI',
      description: 'Create multi-criteria evaluation rubrics, Bloom\'s Taxonomy test questions, and personalized report card remarks in seconds.',
      badge: 'Automated Rubrics',
    },
    {
      id: 'teachers-vid-4',
      title: '04. Interactive Classroom Activities & Slides with Instant Feedback (Curipod)',
      duration: '16:35',
      company: 'TechUp Teachers Network',
      youtubeId: 'G_4lqg9P-L4',
      youtubeUrl: 'https://www.youtube.com/watch?v=G_4lqg9P-L4',
      description: 'Transform static lessons into interactive classroom presentations with live student polls, gamified review quizzes, and collaborative activities.',
      badge: 'Gamified Classroom',
    },
    {
      id: 'teachers-vid-5',
      title: '05. Automated Parent Communication & Professional Emails with AI',
      duration: '15:10',
      company: 'AI For Teachers',
      youtubeId: 'UwSXNiBROgQ',
      youtubeUrl: 'https://www.youtube.com/watch?v=UwSXNiBROgQ',
      description: 'Save 10+ hours weekly: Automate empathetic parent emails, field trip notices, meeting summaries, and report card narratives.',
      badge: 'Admin & Parent Comms',
    },
  ],

  // 14. AI for Students & Academics
  'course-ai-students': [
    {
      id: 'students-vid-1',
      title: '01. Active Recall, Cornell Notes & Spaced Repetition Flashcards with AI',
      duration: '14:35',
      company: 'Dr. Justin Sung',
      youtubeId: 'oI1pLvAx8CE',
      youtubeUrl: 'https://www.youtube.com/watch?v=oI1pLvAx8CE',
      description: 'Master higher-order active recall and deep cognitive encoding: How to prompt AI to test your retrieval without passive review.',
      badge: 'Active Recall • HD',
    },
    {
      id: 'students-vid-2',
      title: '02. The Feynman Technique AI Study Partner: Mastering Hard Concepts',
      duration: '11:50',
      company: 'Scott Luu',
      youtubeId: 'jeXQDbuUFuM',
      youtubeUrl: 'https://www.youtube.com/watch?v=jeXQDbuUFuM',
      description: 'Use AI to practice the Feynman Technique: Spot knowledge blindspots, break down complex concepts, and explain topics in simple language.',
      badge: 'Feynman Technique',
    },
    {
      id: 'students-vid-3',
      title: '03. Step-by-Step Math & Physics Problem Solving with AI Private Tutor',
      duration: '16:20',
      company: 'Radford Mathematics',
      youtubeId: '3V_aa8Fiv0M',
      youtubeUrl: 'https://www.youtube.com/watch?v=3V_aa8Fiv0M',
      description: 'The ultimate student guide to using AI as a private math coach: Socratic hints, verifying steps, formula derivation, and mistake diagnosis without cheating.',
      badge: 'Math Problem Solving',
    },
    {
      id: 'students-vid-4',
      title: '04. Research Paper Summarization, Literature Reviews & Academic Citations',
      duration: '15:45',
      company: 'Dr. Andy Stapleton',
      youtubeId: 'blBJbhZT8gQ',
      youtubeUrl: 'https://www.youtube.com/watch?v=blBJbhZT8gQ',
      description: 'Find academic papers 100x faster, extract core methodologies and findings, conduct literature reviews, and format clean references.',
      badge: 'Academic Research',
    },
    {
      id: 'students-vid-5',
      title: '05. High-Yield Exam Revision Drills, Practice Tests & Mock Questions',
      duration: '17:10',
      company: 'Tom Watchman',
      youtubeId: 'wGmsVH-vyyM',
      youtubeUrl: 'https://www.youtube.com/watch?v=wGmsVH-vyyM',
      description: 'Complete hands-on demo: Generate high-yield practice exam questions, simulate realistic timed mock tests, and pinpoint weak topics before test day.',
      badge: 'High-Yield Mock Drills',
    },
  ],

  // 15. AI for Graphic Designers
  'course-ai-designer': [
    {
      id: 'designer-vid-1',
      title: '01. Master AI Graphic Design & Midjourney Prompt Crafting',
      duration: '24:18',
      company: 'The AI Advantage',
      youtubeId: 'xoZG5WQbgMw',
      youtubeUrl: 'https://www.youtube.com/watch?v=xoZG5WQbgMw',
      description: 'Complete hands-on masterclass for beginners and designers: Prompt engineering, aspect ratios, style references, negative weights, and commercial compositions.',
      badge: 'Design Foundations • 4K',
    },
    {
      id: 'designer-vid-2',
      title: '02. FLUX.1 Commercial Image Generation Masterclass',
      duration: '17:45',
      company: 'Kevin Stratvert',
      youtubeId: 'xOoAlRjTKTw',
      youtubeUrl: 'https://www.youtube.com/watch?v=xOoAlRjTKTw',
      description: 'Master FLUX.1 for photorealistic commercial graphics, anatomy accuracy, and state-of-the-art visual generation.',
      badge: 'FLUX.1 Photorealism',
    },
    {
      id: 'designer-vid-3',
      title: '03. AI Poster Design & Perfect Typography with Ideogram AI',
      duration: '14:30',
      company: 'Nexus Alex',
      youtubeId: 'Euc-Hjchpes',
      youtubeUrl: 'https://www.youtube.com/watch?v=Euc-Hjchpes',
      description: 'Crisp text rendering in posters, typography styling, festival banners, menus, and typography-rich commercial assets without garbled letters.',
      badge: 'Ideogram & Typography',
    },
    {
      id: 'designer-vid-4',
      title: '04. Studio Quality AI Product Photography & Commercial Staging',
      duration: '15:20',
      company: 'Trouvaille Digital',
      youtubeId: 'OL2dQilSrdE',
      youtubeUrl: 'https://www.youtube.com/watch?v=OL2dQilSrdE',
      description: 'Commercial 3D product staging, ambient lighting, packaging mockups, realistic bounce shadows, and clean e-commerce compositions.',
      badge: 'Product Photography',
    },
    {
      id: 'designer-vid-5',
      title: '05. Upscaling AI Images to 20,000px & Commercial Print Standards',
      duration: '18:50',
      company: 'Wade McMaster',
      youtubeId: '6zmksJ6XRWE',
      youtubeUrl: 'https://www.youtube.com/watch?v=6zmksJ6XRWE',
      description: 'Ultra high-res upscaling to 20,000x20,000px, DPI optimization, CMYK offset printing considerations, and prepress export for billboards and packaging.',
      badge: '8K Print & Upscaling',
    },
  ],

  // 16. Enterprise AI Workflow Automation
  'course-ai-automation': [
    {
      id: 'auto-vid-1',
      title: '01. Complete n8n Automation & Autonomous AI Agents Masterclass',
      duration: '38:15',
      company: 'Pratik Joshi • n8n Academy',
      youtubeId: 'OKPOblQ9nfw',
      youtubeUrl: 'https://www.youtube.com/watch?v=OKPOblQ9nfw',
      description: 'Zero-to-hero n8n automation and agent architecture: Core nodes, webhook triggers, Docker self-hosting, and connecting LLM providers.',
      badge: 'Zero to Hero • 4K',
    },
    {
      id: 'auto-vid-2',
      title: '02. Build Your First Autonomous AI Agent with n8n & Tools',
      duration: '22:45',
      company: 'Kevin Stratvert',
      youtubeId: 'dpoMEcXjVH8',
      youtubeUrl: 'https://www.youtube.com/watch?v=dpoMEcXjVH8',
      description: 'Master the n8n AI Agent node: Integrate OpenAI/Gemini, configure dynamic tools, add conversational memory, and trigger automated tasks.',
      badge: 'AI Agent Node',
    },
    {
      id: 'auto-vid-3',
      title: '03. Automated Invoice Processing & Document Pipeline with n8n',
      duration: '18:30',
      company: 'Sajeeb The Analyst',
      youtubeId: '8nCTdoLu_so',
      youtubeUrl: 'https://www.youtube.com/watch?v=8nCTdoLu_so',
      description: 'Automate end-to-end accounting: Extract line items and tax data from PDF invoices, validate totals, and auto-sync records to Google Sheets.',
      badge: 'Invoice & OCR Pipeline',
    },
    {
      id: 'auto-vid-4',
      title: '04. Build a Complete WhatsApp AI Agent with Memory & CRM Sync',
      duration: '24:10',
      company: 'Viren Baid',
      youtubeId: 'CPzqy3M6LbQ',
      youtubeUrl: 'https://www.youtube.com/watch?v=CPzqy3M6LbQ',
      description: 'Connect WhatsApp Cloud API to n8n, handle real-time customer conversations with AI memory, and log qualifying leads directly into CRM databases.',
      badge: 'WhatsApp AI Agent',
    },
    {
      id: 'auto-vid-5',
      title: '05. Advanced AI Agent Architectures, Structured Output & Production Workflows',
      duration: '26:40',
      company: 'Yashica Jain',
      youtubeId: 'w6ZJzP0RBxY',
      youtubeUrl: 'https://www.youtube.com/watch?v=w6ZJzP0RBxY',
      description: 'Enterprise automation blueprints: JSON schema enforcement, multi-agent orchestration, sub-workflow delegation, error handling, and production guardrails.',
      badge: 'Enterprise Guardrails',
    },
  ],

  // 17. Languages: Spoken English
  'course-english-speaking': [
    {
      id: 'eng-vid-1',
      title: '01. Speak English Fluently: 5 Steps to Natural Fluency & Overcoming Hesitation',
      duration: '14:35',
      company: 'Oxford Online English (Official)',
      youtubeId: 'KaA_mxga3PQ',
      youtubeUrl: 'https://www.youtube.com/watch?v=KaA_mxga3PQ',
      description: 'Step-by-step masterclass by Oxford Online English on breaking mental translation loops, speed reading aloud, chunking vocabulary, and speaking naturally without hesitation.',
      badge: 'Oxford English • Verified',
    },
    {
      id: 'eng-vid-2',
      title: '02. Think Fast, Talk Smart: Communication Techniques & Confident Speaking',
      duration: '32:40',
      company: 'Stanford Graduate School of Business',
      youtubeId: 'HAnw168huqA',
      youtubeUrl: 'https://www.youtube.com/watch?v=HAnw168huqA',
      description: 'World-famous Stanford GSB masterclass by Matt Abrahams on spontaneous speaking, managing anxiety, conversational structure (What? So What? Now What?), and practical communication.',
      badge: 'Stanford GSB • Masterclass',
    },
    {
      id: 'eng-vid-3',
      title: '03. English Pronunciation Training: Improve Your Accent & Speak Clearly',
      duration: '14:20',
      company: 'mmmEnglish (Official)',
      youtubeId: 'n4NVPg2kHv4',
      youtubeUrl: 'https://www.youtube.com/watch?v=n4NVPg2kHv4',
      description: 'Targeted pronunciation training with Emma from mmmEnglish: mouth and tongue positioning, syllable stress, vowel sounds, and speaking with clarity.',
      badge: 'mmmEnglish • Pronunciation',
    },
  ],

  // 18. Languages: French
  'course-french-speaking': [
    {
      id: 'fr-vid-1',
      title: '01. Learn French in 30 Minutes: ALL Basics Every Beginner Needs',
      duration: '31:25',
      company: 'FrenchPod101 (Official)',
      youtubeId: '3iezch5YQYo',
      youtubeUrl: 'https://www.youtube.com/watch?v=3iezch5YQYo',
      description: 'High-frequency French conversational foundation: Greetings, essential sentence formulas, numbers, question words, and pronunciation basics without translating in your head.',
      badge: 'FrenchPod101 • CEFR A1',
    },
    {
      id: 'fr-vid-2',
      title: '02. Daily Life French: 100 Words, Expressions & Slow French Conversations',
      duration: '20:45',
      company: 'Easy French (Official)',
      youtubeId: '__Cu2nwgAjA',
      youtubeUrl: 'https://www.youtube.com/watch?v=__Cu2nwgAjA',
      description: 'Real-life conversational practice with native Parisians: Ordering at a boulangerie, asking directions, shopping, and everyday colloquial idioms in natural spoken speed.',
      badge: 'Conversational Fluency',
    },
    {
      id: 'fr-vid-3',
      title: '03. French Pronunciation & Accent Training: Silent Letters, Liaisons & Nasal Vowels',
      duration: '12:30',
      company: 'FrenchPod101 Language Hub',
      youtubeId: '4PvBkp-4bmc',
      youtubeUrl: 'https://www.youtube.com/watch?v=4PvBkp-4bmc',
      description: 'Targeted French phonetics masterclass: Mouth positioning drills, liaisons, silent letters, nasal vowels, and speaking with a clear authentic accent.',
      badge: 'Prononciation & Accent',
    },
  ],

  // 19. Languages: German
  'course-german-speaking': [
    {
      id: 'de-vid-1',
      title: '01. Complete Conversational German: All the Basics You Need (A1–B2)',
      duration: '25:30',
      company: 'GermanPod101 (Official)',
      youtubeId: 'xg60VxyK-9I',
      youtubeUrl: 'https://www.youtube.com/watch?v=xg60VxyK-9I',
      description: 'Complete German grammar and speaking framework: Verb positions, cases (Nominativ, Akkusativ, Dativ), modal verbs, and everyday conversational fluency.',
      badge: 'German Fluency • Goethe',
    },
    {
      id: 'de-vid-2',
      title: '02. Everyday Conversation in Slow German: Natural Dialogues & Listening',
      duration: '10:45',
      company: 'Easy German (Official)',
      youtubeId: 'LwJfk1NUeg4',
      youtubeUrl: 'https://www.youtube.com/watch?v=LwJfk1NUeg4',
      description: 'Real-world dialogues in clear, slow German: Street interviews, everyday conversation etiquette, ordering food, and training natural auditory comprehension.',
      badge: 'Conversational Fluency',
    },
    {
      id: 'de-vid-3',
      title: '03. German Sentence Structure (Satzbau): Word Order & Verb Positions (Hauptsatz)',
      duration: '14:20',
      company: 'YourGermanTeacher (Official)',
      youtubeId: 'O-_cxHx5FD4',
      youtubeUrl: 'https://www.youtube.com/watch?v=O-_cxHx5FD4',
      description: 'Master German sentence construction: Subject-verb-object rules, the V2 verb position, Akkusativ/Dativ placement, and TeKaMoLo time-manner-place principles.',
      badge: 'Satzbau & Grammar',
    },
  ],

  // 20. Public Speaking
  'course-public-speaking-articulation': [
    {
      id: 'speak-vid-1',
      title: '01. How to Speak so That People Want to Listen & Master Articulation',
      duration: '18:50',
      company: 'TED Talks & Toastmasters (Official)',
      youtubeId: 'eIho2S0ZahI',
      youtubeUrl: 'https://www.youtube.com/watch?v=eIho2S0ZahI',
      description: 'World-renowned masterclass on the 7 deadly vocal sins, diaphragmatic breath control, vocal pacing, and speaking so people genuinely want to listen.',
      badge: 'TED Keynote • Verified',
    },
    {
      id: 'speak-vid-2',
      title: '02. Think Fast, Talk Smart: Overcoming Stage Fright & Confident Speaking',
      duration: '32:40',
      company: 'Stanford Graduate School of Business',
      youtubeId: 'HAnw168huqA',
      youtubeUrl: 'https://www.youtube.com/watch?v=HAnw168huqA',
      description: 'Physiological regulation techniques, cognitive reframing, anchoring gestures, and turning nervous energy into charismatic stage presence.',
      badge: 'Stanford GSB • Stage Confidence',
    },
  ],

  // 21. NEET UG 2027
  'course-neet-ug': [
    {
      id: 'neet-vid-1',
      title: '01. NEET Biology (Botany): Introduction to Cells & NCERT Organelle Breakdown',
      duration: '15:30',
      company: 'Amoeba Sisters (Official)',
      youtubeId: '8IlzKri08kk',
      youtubeUrl: 'https://www.youtube.com/watch?v=8IlzKri08kk',
      description: 'Master NEET Biology cell structure and function: Prokaryotic vs eukaryotic differences, organelle functions, membrane transport, and high-yield NCERT diagram-based points.',
      badge: 'NEET Biology (Botany)',
    },
    {
      id: 'neet-vid-2',
      title: '02. NEET Biology (Zoology): Animal Cells & Human Physiology Foundation',
      duration: '11:40',
      company: 'Crash Course Biology (Official)',
      youtubeId: 'cj8dDTHGJBY',
      youtubeUrl: 'https://www.youtube.com/watch?v=cj8dDTHGJBY',
      description: 'Comprehensive tour of animal cell physiology, organelle specialization, cellular respiration, and high-yield NCERT NEET Zoology questions.',
      badge: 'NEET Biology (Zoology)',
    },
    {
      id: 'neet-vid-3',
      title: '03. NEET Physics Checklist: Motion in One Dimension & Kinematics Shortcuts',
      duration: '35:20',
      company: 'Physics Galaxy (Ashish Arora)',
      youtubeId: 'nbdkURzO13U',
      youtubeUrl: 'https://www.youtube.com/watch?v=nbdkURzO13U',
      description: 'Ashish Arora\'s physics revision checklist for NEET: Graphical analysis, instantaneous speed, deceleration traps, and 45-second calculation shortcuts.',
      badge: 'NEET Physics (180M)',
    },
    {
      id: 'neet-vid-4',
      title: '04. NEET Chemistry: The Periodic Table & Chemical Periodicity Trends',
      duration: '11:25',
      company: 'Crash Course Chemistry (Official)',
      youtubeId: '0RRVV4Diomg',
      youtubeUrl: 'https://www.youtube.com/watch?v=0RRVV4Diomg',
      description: 'Master periodic trends, electronegativity, ionization enthalpy, electron gain enthalpy, and transition metal behaviors tested repeatedly in NEET exams.',
      badge: 'NEET Chemistry (180M)',
    },
  ],

  // 22. IIT JEE 2027
  'course-iit-jee': [
    {
      id: 'jee-vid-1',
      title: '01. IIT JEE Mathematics: Linear Algebra, Coordinate Geometry & Vectors',
      duration: '25:30',
      company: '3Blue1Brown (Essence of Math)',
      youtubeId: 'fNk_zzaMoSs',
      youtubeUrl: 'https://www.youtube.com/watch?v=fNk_zzaMoSs',
      description: 'Tackle JEE Advanced multi-concept questions: Vector spaces, linear transformations, dot and cross products, and 3D geometric problem solving.',
      badge: 'JEE Math (100M)',
    },
    {
      id: 'jee-vid-2',
      title: '02. IIT JEE Mathematics: Calculus, Number Theory & Integration Hacks',
      duration: '23:45',
      company: 'Numberphile (Official)',
      youtubeId: 'd8TRcZklX_Q',
      youtubeUrl: 'https://www.youtube.com/watch?v=d8TRcZklX_Q',
      description: 'Locus of conic sections, parametric coordinates speed solutions, modular arithmetic, and definite integration tricks for 99.9 percentile ranking.',
      badge: 'JEE Advanced Math',
    },
    {
      id: 'jee-vid-3',
      title: '03. IIT JEE Physics: Motion in One Dimension & Kinematics Masterclass',
      duration: '35:20',
      company: 'Physics Galaxy (Ashish Arora)',
      youtubeId: 'nbdkURzO13U',
      youtubeUrl: 'https://www.youtube.com/watch?v=nbdkURzO13U',
      description: 'Ashish Arora\'s JEE Physics checklist: Calculus-based kinematics, projectile motion with air drag, relative velocity, and constraint motion.',
      badge: 'JEE Physics (100M)',
    },
    {
      id: 'jee-vid-4',
      title: '04. IIT JEE Chemistry: Periodic Table Trends & Chemical Bonding',
      duration: '11:25',
      company: 'Crash Course Chemistry (Official)',
      youtubeId: '0RRVV4Diomg',
      youtubeUrl: 'https://www.youtube.com/watch?v=0RRVV4Diomg',
      description: 'Complete mastery of periodic properties, hybridization, molecular orbital theory, and inorganic reaction trends for JEE Main and Advanced.',
      badge: 'JEE Chemistry (100M)',
    },
  ],

  // 23. KEAM Prep
  'course-keam-prep': [
    {
      id: 'keam-vid-1',
      title: '01. KEAM 2027: 120 Questions Speed Solving & Arithmetic Protocol',
      duration: '22:15',
      company: 'Numberphile (Official)',
      youtubeId: 'd8TRcZklX_Q',
      youtubeUrl: 'https://www.youtube.com/watch?v=d8TRcZklX_Q',
      description: 'Kerala Engineering Architecture Medical entrance strategy: 150-minute exam pacing, negative mark prevention, and speed calculation shortcuts.',
      badge: 'KEAM Speed Tactics',
    },
    {
      id: 'keam-vid-2',
      title: '02. KEAM Mathematics: Vectors & 3D Coordinate Geometry',
      duration: '25:30',
      company: '3Blue1Brown (Essence of Math)',
      youtubeId: 'fNk_zzaMoSs',
      youtubeUrl: 'https://www.youtube.com/watch?v=fNk_zzaMoSs',
      description: 'Dot and cross product tricks, shortest distance between skew lines, plane intersections, and determinant expansion properties.',
      badge: 'KEAM Mathematics',
    },
    {
      id: 'keam-vid-3',
      title: '03. KEAM Physics: Kinematics & Mechanics Speed Formula Revision',
      duration: '35:20',
      company: 'Physics Galaxy (Ashish Arora)',
      youtubeId: 'nbdkURzO13U',
      youtubeUrl: 'https://www.youtube.com/watch?v=nbdkURzO13U',
      description: 'Solve physics numericals in under 45 seconds using graphical elimination, dimensional analysis, and standard result memory pegs.',
      badge: 'KEAM Physics',
    },
    {
      id: 'keam-vid-4',
      title: '04. KEAM Chemistry: Periodic Table Trends & Chemical Bonding',
      duration: '11:25',
      company: 'Crash Course Chemistry (Official)',
      youtubeId: '0RRVV4Diomg',
      youtubeUrl: 'https://www.youtube.com/watch?v=0RRVV4Diomg',
      description: 'Kerala CEE KEAM Chemistry syllabus: Periodic properties, molecular structure, chemical equilibrium, and high-yield scoring chapters.',
      badge: 'KEAM Chemistry',
    },
  ],

  // 24. AISSEE Sainik School Class 6
  'course-aissee-sainik-6': [
    {
      id: 'sainik6-vid-1',
      title: '01. Class 6 Mathematics: Fast Mental Arithmetic, LCM/HCF & Fractions',
      duration: '26:40',
      company: 'Numberphile (Official)',
      youtubeId: 'd8TRcZklX_Q',
      youtubeUrl: 'https://www.youtube.com/watch?v=d8TRcZklX_Q',
      description: 'Complete breakdown of the 50-question (150 marks) Class 6 Mathematics section: Vedic shortcuts, LCM & HCF fundamental theorem, unitary method, and speed calculations.',
      badge: 'Class 6 Math (150 Marks)',
    },
    {
      id: 'sainik6-vid-2',
      title: '02. Class 6 Intelligence & Non-Verbal Reasoning: Logic & Riddles',
      duration: '21:15',
      company: 'TED-Ed Riddles (Official)',
      youtubeId: '7yDmGnA8Hw0',
      youtubeUrl: 'https://www.youtube.com/watch?v=7yDmGnA8Hw0',
      description: 'Step-by-step visual puzzle solving, mirror images, pattern series completion, embedded figures, and direction sense tests for Class 6.',
      badge: 'Class 6 Reasoning (50 Marks)',
    },
    {
      id: 'sainik6-vid-3',
      title: '03. Class 6 General Knowledge & World History',
      duration: '18:10',
      company: 'Crash Course World History',
      youtubeId: 'Yocja_N5s1I',
      youtubeUrl: 'https://www.youtube.com/watch?v=Yocja_N5s1I',
      description: 'Param Vir Chakra recipients, Indian Army/Navy/Air Force commands, national parks, capitals, monuments, and Class 6 general science trivia.',
      badge: 'Class 6 GK (50 Marks)',
    },
    {
      id: 'sainik6-vid-4',
      title: '04. Class 6 English: 5 Steps to Spoken & Written Fluency',
      duration: '19:30',
      company: 'Oxford Online English (Official)',
      youtubeId: 'KaA_mxga3PQ',
      youtubeUrl: 'https://www.youtube.com/watch?v=KaA_mxga3PQ',
      description: 'Grammar fundamentals: Parts of speech, synonyms, antonyms, spelling correction, sentence re-ordering, and unseen passage strategies.',
      badge: 'Class 6 English (50 Marks)',
    },
  ],

  // 25. AISSEE Sainik School Class 9
  'course-aissee-sainik-9': [
    {
      id: 'sainik9-vid-1',
      title: '01. Class 9 Advanced Mathematics: Vectors & Linear Equations',
      duration: '28:10',
      company: '3Blue1Brown (Essence of Math)',
      youtubeId: 'fNk_zzaMoSs',
      youtubeUrl: 'https://www.youtube.com/watch?v=fNk_zzaMoSs',
      description: 'Master the 50-question (200 marks) Class 9 Mathematics section: Polynomial factorization, linear equations in two variables, circles, quadrilaterals, and surface areas.',
      badge: 'Class 9 Math (200 Marks)',
    },
    {
      id: 'sainik9-vid-2',
      title: '02. Class 9 General Science: Motion in a Straight Line & Physics Laws',
      duration: '22:45',
      company: 'Crash Course Physics',
      youtubeId: 'ZM8ECpBuQYE',
      youtubeUrl: 'https://www.youtube.com/watch?v=ZM8ECpBuQYE',
      description: 'NCERT Class 8 & 9 Physics and Chemistry concepts: Laws of motion, sound waves, atoms and molecules, chemical effects of electric current, and reproduction.',
      badge: 'Class 9 Science (50 Marks)',
    },
    {
      id: 'sainik9-vid-3',
      title: '03. Class 9 Social Studies: Agricultural Revolution & Human History',
      duration: '19:20',
      company: 'Crash Course World History',
      youtubeId: 'Yocja_N5s1I',
      youtubeUrl: 'https://www.youtube.com/watch?v=Yocja_N5s1I',
      description: '1857 Revolt to 1947 Independence movement, Indian Constitution fundamental rights, agriculture types, industries, and parliamentary procedures.',
      badge: 'Class 9 Social (50 Marks)',
    },
  ],

  // 26. Navodaya Vidyalaya JNVST
  'course-navodaya-jnvst': [
    {
      id: 'navodaya-vid-1',
      title: '01. JNVST Mental Ability Test (MAT): Logic & Pattern Riddles',
      duration: '24:20',
      company: 'TED-Ed Riddles (Official)',
      youtubeId: '7yDmGnA8Hw0',
      youtubeUrl: 'https://www.youtube.com/watch?v=7yDmGnA8Hw0',
      description: 'Complete breakdown of the 40-question (50 marks) Mental Ability Test in JNVST: Odd-man-out, pattern completion, and paper folding.',
      badge: 'Mental Ability (50 Marks)',
    },
    {
      id: 'navodaya-vid-2',
      title: '02. JNVST Arithmetic Section: Decimal Numbers & 5-Digit Operations',
      duration: '20:10',
      company: 'Numberphile (Official)',
      youtubeId: 'd8TRcZklX_Q',
      youtubeUrl: 'https://www.youtube.com/watch?v=d8TRcZklX_Q',
      description: 'The 20-question (25 marks) arithmetic section: Number systems, simplification, approximations, and perimeter/area.',
      badge: 'Arithmetic (25 Marks)',
    },
  ],
};

// Map course aliases
COURSE_VIDEO_PLAYLISTS['course-claude-ai'] = COURSE_VIDEO_PLAYLISTS['course-claude-mastery'];
COURSE_VIDEO_PLAYLISTS['course-aissee-sainik'] = COURSE_VIDEO_PLAYLISTS['course-aissee-sainik-6'];

/**
 * Returns the playlist of videos for any given course.
 * If not specifically mapped, provides a tailored set of 3-4 professional lessons.
 */
export function getCourseVideos(courseOrId: Course | string): PortalVideoLesson[] {
  const courseId = typeof courseOrId === 'string' ? courseOrId : courseOrId.id;
  
  if (COURSE_VIDEO_PLAYLISTS[courseId]) {
    return COURSE_VIDEO_PLAYLISTS[courseId];
  }

  // Check matching prefixes or tags
  const idLower = courseId.toLowerCase();
  for (const [key, playlist] of Object.entries(COURSE_VIDEO_PLAYLISTS)) {
    if (idLower.includes(key.replace('course-', '')) || key.includes(idLower.replace('course-', ''))) {
      return playlist;
    }
  }

  // Smart fallback playlist
  const title = typeof courseOrId === 'string' ? courseOrId : courseOrId.title;
  return [
    {
      id: `${courseId}-fallback-vid-1`,
      title: `01. ${title} - Foundations & Core Blueprint Masterclass`,
      duration: '18:30',
      company: 'Nextclasses.in Studio (Official)',
      youtubeId: 'IHOJUJjZbzc',
      youtubeUrl: 'https://www.youtube.com/watch?v=IHOJUJjZbzc',
      description: `Comprehensive fundamentals and actionable framework for ${title}. Step-by-step guidance from zero knowledge to confident mastery.`,
      badge: 'Official Masterclass • 1080p',
    },
    {
      id: `${courseId}-fallback-vid-2`,
      title: `02. Hands-On Practical Implementation & Real-World Projects`,
      duration: '21:15',
      company: 'Nextclasses.in Academy',
      youtubeId: 'WFM2pvj00oc',
      youtubeUrl: 'https://www.youtube.com/watch?v=WFM2pvj00oc',
      description: `Live walkthrough of real-world implementation exercises, project setups, and key productivity workflows for ${title}.`,
      badge: 'Practical Project',
    },
    {
      id: `${courseId}-fallback-vid-3`,
      title: `03. Advanced Strategies, Speed Tactics & Certification Guide`,
      duration: '17:40',
      company: 'Nextclasses.in Certification Wing',
      youtubeId: 'mVXrdvXplj0',
      youtubeUrl: 'https://www.youtube.com/watch?v=mVXrdvXplj0',
      description: `High-yield techniques, common pitfalls to avoid, and step-by-step instructions to obtain your verifiable course certificate.`,
      badge: 'Advanced & Certified',
    },
  ];
}
